Improve legibility of test failures (#534)
When the test suite is run with multiple samples, previously the
individual case seeds, along with the error messages from each
failed case would be interleaved in stdout, making it difficult to
work out which seeds actually failed.

Now, we exit early whenever a single failure is encountered and
only print the failure logs of this single case. This requires
some manipulation of the panic handler, to ensure other cases'
failures that are running concurrently don't sneak through. I hope
I have done a reasonable job of explaining this manipulation in
the comments.

As a test I ran the following command against 420c00b.
```
ZQ_TEST_SAMPLES=100 cargo test --all-targets --all-features -- --exact consensus::block_production
```

Output before this change:
```
running 1 test
test consensus::block_production ... FAILED

failures:

---- consensus::block_production stdout ----
Reproduce this test run by setting ZQ_TEST_RNG_SEED=9180577546468028157
Reproduce this test run by setting ZQ_TEST_RNG_SEED=11152842138600064104
Reproduce this test run by setting ZQ_TEST_RNG_SEED=8898029004173201611
Reproduce this test run by setting ZQ_TEST_RNG_SEED=16297725908176538860
Reproduce this test run by setting ZQ_TEST_RNG_SEED=5188380066871018428
Reproduce this test run by setting ZQ_TEST_RNG_SEED=9672821471740534658
Reproduce this test run by setting ZQ_TEST_RNG_SEED=1973340580707981990
Reproduce this test run by setting ZQ_TEST_RNG_SEED=3185948284866981863
Reproduce this test run by setting ZQ_TEST_RNG_SEED=1924318635786991683
Reproduce this test run by setting ZQ_TEST_RNG_SEED=6919009020223350388
Reproduce this test run by setting ZQ_TEST_RNG_SEED=101518483021215435
Reproduce this test run by setting ZQ_TEST_RNG_SEED=7706094476392694605
Reproduce this test run by setting ZQ_TEST_RNG_SEED=6670965454784609244
Reproduce this test run by setting ZQ_TEST_RNG_SEED=17318769097989637163
Reproduce this test run by setting ZQ_TEST_RNG_SEED=16696760503581666690
Reproduce this test run by setting ZQ_TEST_RNG_SEED=16088950915530708401
Reproduce this test run by setting ZQ_TEST_RNG_SEED=2780264069429727642
Reproduce this test run by setting ZQ_TEST_RNG_SEED=4504950029360081203
Reproduce this test run by setting ZQ_TEST_RNG_SEED=11467515462319601266
Reproduce this test run by setting ZQ_TEST_RNG_SEED=8430540297827517028
Reproduce this test run by setting ZQ_TEST_RNG_SEED=18034733948392288413
Reproduce this test run by setting ZQ_TEST_RNG_SEED=12510669413822035512
Reproduce this test run by setting ZQ_TEST_RNG_SEED=7598171480434585722
Reproduce this test run by setting ZQ_TEST_RNG_SEED=14695005181436126877
Reproduce this test run by setting ZQ_TEST_RNG_SEED=311513366095603746
Reproduce this test run by setting ZQ_TEST_RNG_SEED=1223465937445525821
Reproduce this test run by setting ZQ_TEST_RNG_SEED=4389316195981588184
Reproduce this test run by setting ZQ_TEST_RNG_SEED=2458818106516966588
Reproduce this test run by setting ZQ_TEST_RNG_SEED=9356725731490518217
Reproduce this test run by setting ZQ_TEST_RNG_SEED=8867343627348510873
Reproduce this test run by setting ZQ_TEST_RNG_SEED=13096423205312839363
Reproduce this test run by setting ZQ_TEST_RNG_SEED=933137166078286932
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: condition was still false after 500 ticks', zilliqa/tests/it/consensus.rs:126:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'consensus::block_production' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(33), ...)', zilliqa/tests/it/consensus.rs:94:1
Reproduce this test run by setting ZQ_TEST_RNG_SEED=17189366594246129458
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: condition was still false after 500 ticks', zilliqa/tests/it/consensus.rs:126:10
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: condition was still false after 500 ticks', zilliqa/tests/it/consensus.rs:126:10
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: condition was still false after 500 ticks', zilliqa/tests/it/consensus.rs:126:10
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: condition was still false after 500 ticks', zilliqa/tests/it/consensus.rs:126:10
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: condition was still false after 500 ticks', zilliqa/tests/it/consensus.rs:126:10
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: condition was still false after 500 ticks', zilliqa/tests/it/consensus.rs:126:10

failures:
    consensus::block_production

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 16 filtered out; finished in 23.36s
```

Output after this change:
```
running 1 test
test consensus::block_production ... FAILED

failures:

---- consensus::block_production stdout ----
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: condition was still false after 500 ticks', zilliqa/tests/it/consensus.rs:120:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Reproduce this test run by setting ZQ_TEST_RNG_SEED=14592242645420579345

failures:
    consensus::block_production

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 16 filtered out; finished in 21.87s
```